print("Hi \"Python\"")
print('Hi "Python"')
print('Hi \'Python\'')
print("Path: C:\\Users\\Winnie")
print("Message1")
print()
print("Message2")
print("Message3\n") 
print("Message4")
print("Message5\n\n\n")
print("Message6")
print("Message7\n\n\nMessage8")
print("Message9\tMessage10")